import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

type LinkProps = { title: string, path: string }

const linkList: LinkProps[] = [
  { title: "All Algos", path: "/" },
  { title: "Sort", path: "/sort" },
  { title: "Search", path: "/search" },
  { title: "Pathfind", path: "/pathfind" },
]



const HeaderLink = ({ title, path }: LinkProps) => {
  return (
    <a href={path}>
      <div className="flex flex-col rounded m-2 p-2">
        {title}
      </div>
    </a>
  )
}
const HeaderMenu = () => {
  return (
    <div className="flex flex-row">
      {linkList.map(
        (linkProps) => {
          return (
            <HeaderLink {...linkProps} />
          )
        }
      )
      }
    </div>
  )
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderMenu />
        {children}</body>
    </html>
  );
}
